### ISSUE TITLE
[Feature Request]: Add Tags to TechGroups

### ISSUE THREAD

**Issue by joeriddles** [SpokaneTech/SpokaneTech_Py#108]
### Description

- [x] Add a Tag relationship to TechGroups
- [x] Display TechGroup tags on TechGroups list cards and details
- [x] Display TechGroup tags on Event list cards and details **if the events don't have any Tags of their own**
- [x] Filtering Events by tags should include TechGroup tags

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KGB33** [comment]
Closed by #109
