### ISSUE TITLE
View upcoming events

### ISSUE THREAD

**Issue by joeriddles** [SpokaneTech/SpokaneTech_Py#11]
As a visitor of SpokaneTech.org, I want to be able to see a chronologically (soonest first) sorted listed of upcoming events in the Spokane area.

### Examples
https://www.meetup.com/find/
![image](https://github.com/SpokaneTech/SpokaneTech/assets/19392916/2e914ac9-7e80-4d96-ae0c-037aa2000ce7)

https://www.eventbrite.com/d/wa--spokane/all-events/
![image](https://github.com/SpokaneTech/SpokaneTech/assets/19392916/0ee68e24-cd14-42a4-8341-2788d52254d5)

**Comment by VidyaYadavv1519** [comment]
hiiii can you assign me this issue ??
