### ISSUE TITLE
[Bug]: Fix CSRF token verification for set_timezone

### ISSUE THREAD

**Issue by joeriddles** [SpokaneTech/SpokaneTech_Py#115]
### Descriription

~~Maybe the handy helpers base template isn't setting the CSRF token before we use it?~~

https://github.com/SpokaneTech/SpokaneTech_Py/blob/e2df8c48e101e0fea627cf2d7a140961a7a3e6a9/src/templates/spokanetech/base.html#L25

It looks like the handy helpers base template does not include `{% csrf_token %}`:

https://github.com/davidslusser/django-handyhelpers/blob/7cdcca1fbf83c984bc4a6b8d116c9b2ddbc33020/handyhelpers/templates/handyhelpers/handyhelpers_base.htm

We can just add it to our base.html file.

<img width="1495" alt="image" src="https://github.com/user-attachments/assets/5484f27f-c1af-47e7-9310-25dffe408592">

### Expected behavior

No CSRF verification failed

### Steps to reproduce the behavior

1. Open a private window
2. Open https://spokanetech.org/events
3. Open the devtools console and see the error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidslusser** [comment]
will default timezone to pacific for all displays; users can override with use settings
