### ISSUE TITLE
Determine code styling tools

### ISSUE THREAD

**Issue by joeriddles** [SpokaneTech/SpokaneTech_Py#12]
- Formatter ([black](https://black.readthedocs.io/en/stable/), [ruff](https://docs.astral.sh/ruff/), [isort](https://pycqa.github.io/isort/))
- Linter ([flake8](https://flake8.pycqa.org), [ruff](https://docs.astral.sh/ruff/), [radon](https://radon.readthedocs.io/en/latest/))
- Type checker ([pyright](https://microsoft.github.io/pyright/), [mypy](https://mypy-lang.org/))
- Security ([bandit](https://bandit.readthedocs.io/en/latest/), [safety](https://safetycli.com/product/safety-cli)) 
- Testing (pytest, unittest)

**Comment by KGB33** [comment]
I've heard great things about `ruff` for linting, and using it for both linting and formatting seems super convenient.

For type checking I'd prefer `pyright`. 

Is there any reason `bandit` and `safety` can't both be run? Especially in CI? 

I don't think there is any reason to use `unittest` over `pytest`.

**Comment by joeriddles** [comment]
I also like pyright and that fact that it's what's used by default in VS Code through [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance).

bandit and safety could both be used, for sure.

There's a few reasons I can think of to use pytest over/with unittest:
- pytest is a better test runner than unittest and also handles unittest tests
- unittest can be a funky due to how old it is and it's Java-inspired nature
- pytest fixtures are powerful
- Way more plugins for pytest

**Comment by davidslusser** [comment]
my two cents, strongly recommend ruff, bandit, safety, pytest and others. I'd also suggest getting coveralls or codecov setup when we're ready for unittesting. I also have github composite actions available that are super easy to add to any repo.  I use these on all my open source stuff.  You can see examples in this repo: https://github.com/djangoaddicts/django-pygwalker.
