### ISSUE TITLE
Upgrade Dagger CLI/Engine to latest version

### ISSUE THREAD

**Issue by KGB33** [SpokaneTech/SpokaneTech_Py#122]
I've ran into two issues running the current Dagger setup on the latest version:

The `verbose` argument on `all-linters` is being superseded by the builtin `verbose` flag, leading to the following error: 
```
error: parse selections: parse field "allLinters": init arg "verbose" value as dagql.Boolean (Boolean!) using dagql.Boolean: cannot create Boolean from int64
```

Additionally, `requirments/dev.txt` isn't installed to the container returned by `dev`, so Django cannot start due to `ModuleNotFoundError: No module named 'debug_toolbar'` errors.

If you've run into any other errors let me know and I'll try to include fixes in the PR.

**Comment by joeriddles** [comment]
Whoops, I might've broken this when migrating to Azure. Thought all the CI checks were passing with my changes.

**Comment by KGB33** [comment]
> Whoops, I might've broken this when migrating to Azure. Thought all the CI checks were passing with my changes.

@joeriddles your Azure changes didn't break anything, the CI is pinned to version `0.10.x`. 

Although, now that we're off Fly and don't need the `Dockerfile` to deploy I think we replicate everything but `az-docker-compose.yaml` in Dagger (I assume Azure uses it to deploy the app).

Plus, I think I'll be able to shorten the commands during this upgrade. I.e. `dagger call --req requirements.lock --src src all-linters --dev-req requirements.dev.lock --pyproject pyproject.toml` to `dagger call all-linters`.
