### ISSUE TITLE
[Feature Request]: Investigate using Dagger for CI

### ISSUE THREAD

**Issue by joeriddles** [SpokaneTech/SpokaneTech_Py#22]
### Description

Investigate using [Dagger](https://dagger.io/dagger-engine) for GitHub Actions as noted here: https://github.com/SpokaneTech/SpokaneTech_Py/issues/3#issuecomment-1919456625

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KGB33** [comment]
# Demo

I have a basic demo [here](https://github.com/KGB33/SpokaneTech_Py/tree/22-dagger-ci). Please let me know (here, or ping in Discord) if you have any questions.

To get up and running, install Dagger v0.9.11 (currently the latest release) [from here](https://docs.dagger.io/cli/465058/install) and Docker. Then clone my repo and list the available 'functions' using the following commands:

```
git clone git@github.com:KGB33/SpokaneTech_Py.git KGB33_SpokaneTech_Py
cd KGB33_SpokaneTech_py
git switch 22-dagger-ci
dagger -m ci functions
```

To call a function the repository needs to be passed using the `--dir` flag, i.e. `dagger -m ci --dir . call bandit`

The functions are defined in `ci/src/main.py`, and the referance Dagger documentation is [here](https://dagger-io.readthedocs.io/en/sdk-python-v0.9.11/).

For IDE autocomplete:

```
cd ci
dagger develop
python -m venv .venv
source .venv/bin/activate
pip install -e ./sdk
```

I have an example of using Dagger with GitHub Actions [here](https://github.com/KGB33/blog.kgb33.dev/blob/main/.github/workflows/build.yaml).


---

# Overall pros & cons

Pros:
  - CI/CD is written in Python.
  - Containerization means that if it works locally it'll work in CI/Production.

Cons:
  - Requires Docker, I know this can be a pain to setup on Windows.
  - Fly uses Dockerfiles, Dagger produces Docker images.
  - The CLI is excessively wordy.
  - Dagger is in beta, no `1.0` release yet.

**Comment by joeriddles** [comment]
@KGB33 this is awesome! Could you demo it at the next coffee & code or meetup??

**Comment by KGB33** [comment]
Sure! I can demo it at the meetup on March 19th.
