### ISSUE TITLE
Stand up basic website

### ISSUE THREAD

**Issue by joeriddles** [SpokaneTech/SpokaneTech_Py#3]
As a user, I want [SpokaneTech.org](https://SpokaneTech.org) to resolve to a website. Currently it resolves to nothing :)
- [x] Harden security -> https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
- [x] Need a webapp to deploy
- [x] Configure domain registrar (@joeriddles likely needs to do this)

**Comment by joeriddles** [comment]
Options for deploying to include:
- DigitalOcean droplet
- Azure app service
- AWS EC2 ?
- Python Anywhere
- fly.io
- ...

**Comment by KGB33** [comment]
I did a quick price comparison for the potential clouds; Fly.io is roughly $6/month (after free usage), and DigitalOcean is $4/month. The others are all in the $12+/month range. 

I'm leaning towards Fly.io, It provides managed SSL certs and enables easy postgres setup.

---

In discord you mentioned setting up GitHub Actions for CD. I like to use something like [Dagger](https://dagger.io/dagger-engine) to script the CI/CD in Python, then call it from GH Actions.

**Comment by joeriddles** [comment]
> I'm leaning towards Fly.io, It provides managed SSL certs and enables easy postgres setup.

@KGB33 fly sounds good to me. I have a bunch of credits that we can use. We may want to use [Supabase Postgres + Fly](https://fly.io/docs/reference/supabase/) instead of Fly's unmanaged Postgres database.

> In discord you mentioned setting up GitHub Actions for CD. I like to use something like [Dagger](https://dagger.io/dagger-engine) to script the CI/CD in Python, then call it from GH Actions.

I haven't used Dagger before but it looks cool!

**Comment by joeriddles** [comment]
@KGB33 I added a simple workflow to deploy to Fly.io just to get us off the ground so people can see their work deployed once it's merged. I would love for us to look into using Dagger if you want to see if we can migrate the deploy command to using that!

**Comment by joeriddles** [comment]
Closing with a new issue for Dagger: https://github.com/SpokaneTech/SpokaneTech_Py/issues/22
