### ISSUE TITLE
[Feature Request]: add a blog app 

### ISSUE THREAD

**Issue by davidslusser** [SpokaneTech/SpokaneTech_Py#33]
### Description

Create a new django app for blog like articles. In this app members could write/post articles on technical topics. Consider features like tags, stars and comments per blog post. 

reference:
https://djangocentral.com/building-a-blog-application-with-django/ 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joeriddles** [comment]
We should consider using https://wagtail.org/ for this
